name: Generate Contribution Snake

on:
  # every 6 hours
  schedule:
    - cron: "0 */6 * * *"    # runs at 00:00, 06:00, 12:00, 18:00 UTC 
  
  # manual trigger
  workflow_dispatch:        # lets you hit “Run workflow” by hand 

  # also on every push to main
  push:
    branches:
      - main               # change to your default branch name 

jobs:
  generate:
    permissions:
      contents: write       # grants the action push rights to branches 
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3   # SVG-only action 
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg               # light version 
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  # dark version :

      - name: publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # deploys `dist/` to `output` 
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

