name: Generate Contribution Snake

# Run on a schedule and allow manual dispatch
on:
  schedule:
    - cron: '0 0 * * *'        # daily at midnight UTC
  workflow_dispatch:           # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG & GIF
        uses: Platane/snk@v3.3.0     # use v3 tag for stability
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=green&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      - name: Push outputs to “output” branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
