name: Generate Contribution Snake

on:
  # every 6 hours
  schedule:
    - cron: "0 */6 * * *"    # runs at 00:00, 06:00, 12:00, 18:00 UTC :contentReference[oaicite:0]{index=0}
  
  # manual trigger
  workflow_dispatch:        # lets you hit “Run workflow” by hand :contentReference[oaicite:1]{index=1}

  # also on every push to main
  push:
    branches:
      - main               # change to your default branch name :contentReference[oaicite:2]{index=2}

jobs:
  generate:
    permissions:
      contents: write       # grants the action push rights to branches :contentReference[oaicite:3]{index=3}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3   # SVG-only action :contentReference[oaicite:4]{index=4}
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg               # light version :contentReference[oaicite:5]{index=5}
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  # dark version :contentReference[oaicite:6]{index=6}

      - name: publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # deploys `dist/` to `output` :contentReference[oaicite:7]{index=7}
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

